apiVersion: apps/v1
kind: Deployment
metadata:
  name: qod-web
  labels:
    app: qod-web
    tier: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: qod-web
  template:
    metadata:
      labels:
        app: qod-web
    spec:
      containers:
        - name: qod-web
          image: ibmicpcoc/qod-web
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: QOD_API_URL
              value: "http://qod-api:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: qod-web
  labels:
    app: qod-web
    tier: ui
spec:
  type: ClusterIP
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
  selector:
    app: qod-web
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: qod
  namespace: qod
spec:
  path: /
  to:
    kind: Service
    name: qod-web
  port:
    targetPort: http
    